refactor: release process

diff --git a/.github/workflows/publish-stable-extension.yml b/.github/workflows/publish-stable-extension.yml
--- a/.github/workflows/publish-stable-extension.yml
+++ b/.github/workflows/publish-stable-extension.yml
@@ -1,4 +1,4 @@
-name: Publish Extensions
+name: Publish Stable Extensions
 on:
   push:
     tags:
@@ -9,7 +9,7 @@ env:
   SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
 
 jobs:
-  pre_run:
+  pre-run:
     runs-on: ubuntu-latest
     steps:
       - name: Cancel Previous Runs
@@ -17,17 +17,16 @@ jobs:
         with:
           access_token: ${{ github.token }}
 
-  publish_chrome_extension:
+  publish-chrome-extension:
     name: Publish Chrome extension
     runs-on: ubuntu-latest
     if: startsWith(github.ref, 'refs/tags/v')
     needs:
-      - pre_run
+      - pre-run
     outputs:
       publish_status: ${{ steps.publish-chrome.outputs.publish_status }}
     steps:
-      - name: Check out Git repository
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
       - uses: actions/cache@v2
         id: cache-node-modules
@@ -63,14 +62,14 @@ jobs:
           CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
           REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
 
-  publish_firefox_extension:
+  publish-firefox-extension:
     name: Publish Firefox extension
     runs-on: ubuntu-latest
     env:
       MINIFY_PRODUCTION_BUILD: true
     if: startsWith(github.ref, 'refs/tags/v')
     needs:
-      - pre_run
+      - pre-run
     outputs:
       publish_status: ${{ steps.publish-firefox.outputs.publish_status }}
     steps:
@@ -112,10 +111,10 @@ jobs:
   post_run:
     runs-on: ubuntu-latest
     needs:
-      - publish_chrome_extension
-      - publish_firefox_extension
+      - publish-chrome-extension
+      - publish-firefox-extension
     steps:
       - name: Publish Statuses
         run: |
-          echo "::warning::Firefox Publish Status: $([[ "${{ needs.publish_firefox_extension.outputs.publish_status }}" = "0" ]] && echo 'SUCCESS' || echo 'FAILED')"
-          echo "::warning::Chrome Publish Status: $([[ "${{ needs.publish_chrome_extension.outputs.publish_status }}" = "0" ]] && echo 'SUCCESS' || echo 'FAILED')"
+          echo "::warning::Firefox Publish Status: $([[ "${{ needs.publish-firefox-extension.outputs.publish_status }}" = "0" ]] && echo 'SUCCESS' || echo 'FAILED')"
+          echo "::warning::Chrome Publish Status: $([[ "${{ needs.publish-chrome-extension.outputs.publish_status }}" = "0" ]] && echo 'SUCCESS' || echo 'FAILED')"
