fix: remove error message

diff --git a/.github/workflows/publish-extensions.yml b/.github/workflows/publish-extensions.yml
--- a/.github/workflows/publish-extensions.yml
+++ b/.github/workflows/publish-extensions.yml
@@ -118,7 +118,7 @@ jobs:
         continue-on-error: true
         id: publish-chrome
         run: |
-          yarn chrome-webstore-upload upload --auto-publish --source stacks-wallet-chromium.zip
+          yarn chrome-webstore-upload upload --source stacks-wallet-chromium.zip
           echo "::set-output name=publish_status::${?}"
         env:
           EXTENSION_ID: ${{ secrets.CHROME_APP_ID }}
@@ -129,10 +129,11 @@ jobs:
   publish_firefox_extension:
     name: Publish Firefox extension
     runs-on: ubuntu-latest
+    if: false
+    # if: startsWith(github.ref, 'refs/tags/v')
     env:
       MINIFY_PRODUCTION_BUILD: true
       TARGET_BROWSER: firefox
-    if: startsWith(github.ref, 'refs/tags/v')
     needs:
       - pre-run
       - create-github-release
@@ -171,13 +172,13 @@ jobs:
           WEB_EXT_API_KEY: ${{ secrets.FIREFOX_API_KEY }}
           WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
 
-  post_run:
-    runs-on: ubuntu-latest
-    needs:
-      - publish_chrome_extension
-      - publish_firefox_extension
-    steps:
-      - name: Publish Statuses
-        run: |
-          echo "::warning::Firefox Publish Status: $([[ "${{ needs.publish_firefox_extension.outputs.publish_status }}" = "0" ]] && echo 'SUCCESS' || echo 'FAILED')"
-          echo "::warning::Chrome Publish Status: $([[ "${{ needs.publish_chrome_extension.outputs.publish_status }}" = "0" ]] && echo 'SUCCESS' || echo 'FAILED')"
+  # post_run:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - publish_chrome_extension
+  #     # - publish_firefox_extension
+  #   steps:
+  #     - name: Publish Statuses
+  #       run: |
+  #         # echo "::warning::Firefox Publish Status: $([[ "${{ needs.publish_firefox_extension.outputs.publish_status }}" = "0" ]] && echo 'SUCCESS' || echo 'FAILED')"
+  #         echo "::warning::Chrome Publish Status: $([[ "${{ needs.publish_chrome_extension.outputs.publish_status }}" = "0" ]] && echo 'SUCCESS' || echo 'FAILED')"
